name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    env:
      GITHUB_TOKEN: '${{ github.token }}'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.0.0'
      - run: |
          yarn
      - run: |
          yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, ubuntu-22.04-arm, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          cache_key: build-test-${{ matrix.os }}
